### ISSUE TITLE
NHL Games Load Structure, but No Stream

### ISSUE THREAD

**Issue by imbeinabout** [crobibero/Emby.Plugins.LazyMan#10]
NHL games load in the interface, but when I drill down to the stream itself, it gives the error "Not available yet" even though the game has already started.  This is consistent across all devices.

To test that it is an issue with the plugin and not LazyMan, I tried to stream the game on my computer with the native LazyMan app and could stream all the games in progress with no problems.  

Any ideas on a fix?  Thanks.

**Comment by crobibero** [comment]
Try running the task “Refresh internet channels”

**Comment by imbeinabout** [comment]
That worked.  Thanks!
