### ISSUE TITLE
NHL Feeds not working

### ISSUE THREAD

**Issue by HocEman** [crobibero/Emby.Plugins.LazyMan#11]
Streams will not start playing on Emby.  I can see the plugin and can drill down to a game and select a quality, but it never starts to play.  I have attached the Emby Log for reference.

Just for testing I tried your plugin for Jellyfin and that is working, so I think it is something with Emby.  I would prefer to use Emby over Jellyfin.

Thank you for your time!

[Emby_log.txt](https://github.com/crobibero/Emby.Plugins.LazyMan/files/3694516/Emby_log.txt)

**Comment by crobibero** [comment]
Can you enable debug mode and try again?

**Comment by HocEman** [comment]
Sure, tried again with same result.  Attached log with debug enabled.

Thank you!

[Emby_log_Debug.txt](https://github.com/crobibero/Emby.Plugins.LazyMan/files/3714963/Emby_log_Debug.txt)

**Comment by crobibero** [comment]
@HocEman- what client are you trying to play the stream on?

@jlachesk- can you try playing through the browser?

**Comment by jlachesk** [comment]
@crobibero I'll make a note to myself to try it for the next game. I won't be around later today to try, but probably tomorrow afternoon.

**Comment by HocEman** [comment]
I was just using my browser - Chrome v77.0.3865.90 (it now just updated to v77.0.3865.120 but still have the same result)

I also just tried with the ios app and received a "No compatible streams are currently available" error

**Comment by jlachesk** [comment]
Just tried via Browser and Android App with a game from yesterday. Played on Browser fine (took ~60s to start playing), Android App just spun forever.

Chrome: Version 77.0.3865.90 (Official Build) (64-bit)
App: Emby for Android Mobile 3.0.82

**Comment by HocEman** [comment]
@jlachesk What stream did you use?  I have tried Lazyman->NHL->10/10/2019->New Jersey Devils vs Edmonton Oilers->NHLTV-HOME-> and then have tried 780p 60fps, 780p, 540p, 504p All with the same result.  I have tried other games as well.

**Comment by crobibero** [comment]
How are you hosting Emby?

**Comment by HocEman** [comment]
Emby Docker on UnRaid

**Comment by mathg** [comment]
I had the same issue and changing my Max bitrate playback settings to a defined value instead of auto made it work for me.

**Comment by jlachesk** [comment]
@mathg Was that a setting on the Server or Client side? Want to give this a shot.

**Comment by jlachesk** [comment]
@HocEman I tried the Pens game from 10/10/2019, but they all seem to be working when I play it via browser.

**Comment by crobibero** [comment]
@jlachesk That's a client sided option.

**Comment by jlachesk** [comment]
I spent some time messing around w/ playing streams via the Android App, and here's what I've discovered as a consistent way of getting streams to play:

- Navigate to the stream (I used the 720p 60fps versions for all tests)
- Start the stream, get the spinning loading circle in the middle of the screen
- Change "Version" from "720p 60fps" to "undefined" and hit play
- Stream starts in 5-10s

If I just leave the version as "720p 60fps" the spinning loading circle will just keep spinning. I waited 10 minutes and nothing happened.

I haven't look at the logs at all to figure out what's happening when I switch versions and hit play again, but this has worked 100% of the time for me.

I'm not sure if I'll be able to do something similar w/ the Roku app (kids have commandeered the TV, so will have to wait to test).

**Comment by jlachesk** [comment]
@crobibero I only get the Settings gear _after_ a stream starts playing. My hanging issue happens before it switches to the media player, so I can't get to the bitrate option. Using the steps in my last post, I'm able to get streaming to start even when left on Auto (4K 120mpbs).

**Comment by crobibero** [comment]
That's interesting, it looks like the web client defaults to the undefined stream. Not sure where the second stream is coming from though

**Comment by mathg** [comment]
@jlachesk That was a setting on the client side, specifically from atv for me. I changed it to match my internet connection speed (~35mb/s) and it worked. I tried putting it higher, like 40mb/s and over and it never worked. Playback flashed black and closed immediately.

**Comment by vizzo110** [comment]
Seeing the same issue when loading from Roku. Can't get the stream to start from the Roku UI.

My current workaround is to load it in the web browser and 'cast' it to the Roku Emby app.

**Comment by HocEman** [comment]
Initially I was using the linuxserver version of the docker and it was not working.  I switched to the official docker as part of my troubleshooting, before I opened this issue. 

I totally missed your note in the readme stating that the official docker does not work correctly.

I went back to the linuxserver version of the docker - added the IPs to the host file - and set the "refresh Internet Channels" schedule task to run every 30 mins.

The streams are now playing in my browser!  They do not start unless I click the gear and change the quality of the stream.  It does not seem to matter what quality I choose, just as long as it changes.  For example, I select the feed and click on the play button, and nothing happens.  I click on the gear and the quality is set to "auto" - I change it to 720p - 4Mbps and the stream starts to play.  I can even change it back to "auto" and it still plays, so it seems like changing the quality "kicks off" the stream for some reason.

I am also having success on the iOS app as well, but I do need to use @jlachesk tip and select the "undefined" version.

I am happy things are now working, and the "tweaks" that are necessary are easy and not a problem at all.

Thank you @crobibero for your continued work on this plugin!

Thank you @jlachesk and @mathg your suggestions to get this working!

**Comment by crobibero** [comment]
Glad you got it working! I’m going to mark this as closed and move the debug steps to the readme when I get a chance.

**Comment by uberfunk** [comment]
@mathg I had to do the same on Apple TV to get it to work (set the bitrate to 35MB/s). Any higher and it wouldn't load.

But in the last week or so, everything just stopped working. Checked if the IP had changed for powersports and it did. Changed the hosts file and now i have 5 tiles in Lazyman. **MLB**, **NHL**, **mf.svc.nhl.com IP ERROR**, **mlb-ws-mf.media.mlb.com IP ERROR**, and **playback.svcs.mlb.com IP ERROR**. Tried uninstalling Emby entirely and set everything up fresh but it still can't resolve the new IPs..?

Selecting feeds in NHL does nothing. Just spins. Has this happened to anyone else? Anyone have suggestions?

Just a standard Windows 10 PC with Emby 4.2.1.0

**Comment by crobibero** [comment]
@uberfunk I don't believe the IP changed, or at least I haven't changed my Emby/Jellyfin setup in a few weeks. If you're seeing the IP ERROR tiles then Emby is not seeing the correct IPs.

**Comment by uberfunk** [comment]
Weird....is the new IP for powersports.ml not 195.20.50.76? That's what i'm getting when i ping it...
Can someone verify? What IP are you using @crobibero?

**Comment by crobibero** [comment]
@uberfunk the url you need to use to get the IP is `nhl.freegamez.ga`

**Comment by uberfunk** [comment]
@crobibero That fixed it! The IP ERROR tiles disappeared and streams are working again.
Was there an announcement somewhere that the domain had changed?!

**Comment by vraicovi** [comment]
@crobibero Mine is working on the IP address above, the streams take a long time to load, but they load.  Should we now be using nhl.freegamez.ga regardless?

**Comment by uberfunk** [comment]
Looks like it's a permanent change. It's even referenced in [chiefy's code](https://github.com/nomego/Lazyman.bundle/pull/72) to fix the Plex Lazyman plugin.

**Comment by heym0n** [comment]
NHL Feeds are not working for me after updating everything (deleting and reinstalling).

Method of stream is via RMP DLNA SERVER.  

I m able to get to the Feed selection (Home Away Multi-Cam) but, when I select any of them, it tries to retrieve and errors in File Not Playable.  An unexpected problem nut not server timeout or HTTP error has been detected.   

Steps I have taken:
Deleted the Lazyman bundle within the plugin folder while having the plex server NOT running.
Used Git to clone chiefy's .git bundle of lazyman to the plugin folder.
Deleted HOSTS file, created a new one with HOSTSman.  
Updated HOSTS' entry with freegamez IP with the pinged address.
Deleted all old HOST entries.

Any ideas would rock!

**Comment by crobibero** [comment]
@heym0n- This is for the Emby plugin, I have no knowledge of the Plex plugin

**Comment by crobibero** [comment]
I just released an update to fix the `undefined` stream, and to fix stream start times. Please give it a try and report back
