### ISSUE TITLE
Save Stream for Delayed Playback

### ISSUE THREAD

**Issue by ramonleon627** [crobibero/Emby.Plugins.LazyMan#12]
The current Lazyman app has an option to Save the stream as a file.  This is useful for when I want to watch an NHL game from the beginning and fast forward through commercials and intermission.  However, since it is recorded outside of Emby, I have to manually refresh within Emby to access the newly recorded parts.  From what I understand, if the Emby recording engine is used, it will be aware that it is an active recording and continue to play through without manual intervention.

Is it possible to include the Save Stream feature from the Lazyman app in the Emby plugin utilizing the Emby recording engine?

**Comment by crobibero** [comment]
I don't think this is possible, sorry
