### ISSUE TITLE
"Error creating Emby.Plugins.LazyMan.LazyManChannel"

### ISSUE THREAD

**Issue by mattplotas** [crobibero/Emby.Plugins.LazyMan#13]
[log.txt](https://github.com/crobibero/Emby.Plugins.LazyMan/files/3861010/log.txt)
Running in a freenas jail with Emby 4.1.1.0, Lazyman shows as installed in the plugins menu of the server dashboard, with the only option being to uninstall.
Attached is the full logfile which has a bit more insight that I don't particularly understand.

Thanks!

**Comment by crobibero** [comment]
There is no configuration, just open up the lazy man channel

**Comment by crobibero** [comment]
Sorry I didn’t fully read the report. I’ve never seen this bug so I’ll probably have to ask the Emby devs for assistance

**Comment by crobibero** [comment]
I think the load error is because you are running a version of Emby that is lower then `4.2.0.40`, the version of Emby that I targeted. Is it possible for you to update?

**Comment by mattplotas** [comment]
I am in the midst of a wrestling match with freenas/emby trying to get it updated and will report back when I'm victorious :D

**Comment by mattplotas** [comment]
Got it updated and streams appear to be working, albeit with a consistent 1-2 minute loading time after selecting a quality. I appreciate your work on this.

**Comment by crobibero** [comment]
Glad to hear. I think I know what causes the delay but I need input from the devs, will reach out to them shortly.
