### ISSUE TITLE
Emby search suggestions filled with game streams

### ISSUE THREAD

**Issue by puzzledsam** [crobibero/Emby.Plugins.LazyMan#16]
With the LazyMan plugin installed, Emby’s search suggestions are crowded with the sports streams of various qualities (image below).

![3ECD5712-AB4F-4D1F-921A-6E5A6C56E738](https://user-images.githubusercontent.com/16420610/71315223-5a8c0a00-241d-11ea-8647-d3838ae3dd41.png)

Would it be possible to exclude the games from search? I would also prefer if games were not indexed as movies in search.

**Comment by crobibero** [comment]
Due to recent changes in how Emby channels work there is nothing I can do about this. I tried setting the game stream to be a "Tv Extra" but it still showed in the movie search

**Comment by puzzledsam** [comment]
I see. Thanks for the help.
