### ISSUE TITLE
MLB does not show streams/games

### ISSUE THREAD

**Issue by pythonhockey** [crobibero/Emby.Plugins.LazyMan#2]
NHL seems to be working great for me, but MLB is having issues. On 4/23, no games show up at all. On 4/24, the list of games show up, but there are no streams.

If there’s any testing I can do, please let me know.

**Comment by crobibero** [comment]
Please try the new release.

**Comment by pythonhockey** [comment]
Getting closer. Both show all the feeds, but I'm seeing some weird behavior. I get an error with every stream I try to start, which I've attached. The MLB feeds show up, but when I drill down to the quality options, I get some foreign films, none of which I own. 
<img width="1270" alt="Screen Shot 2019-04-24 at 9 15 42 PM" src="https://user-images.githubusercontent.com/15678158/56703303-24538a80-66d6-11e9-8dc1-52e4171bcbe9.png">
<img width="412" alt="Screen Shot 2019-04-24 at 9 14 10 PM" src="https://user-images.githubusercontent.com/15678158/56703304-24538a80-66d6-11e9-9349-b92f8b74301d.png">
<img width="1319" alt="Screen Shot 2019-04-24 at 9 13 55 PM" src="https://user-images.githubusercontent.com/15678158/56703305-24538a80-66d6-11e9-84d9-8fbb8894b048.png">

**Comment by crobibero** [comment]
Does NHL still work for you?

**Comment by pythonhockey** [comment]
Unfortunately no. Same error as picture two.

**Comment by pythonhockey** [comment]
I’m on Ubuntu 16.04 if that helps. Happy to test anything you need. Thanks for the work on this!

**Comment by crobibero** [comment]
I got LazyMan working through Jellyfin but still no luck for Emby. Really not sure how to fix it since the plugins have the same code
