### ISSUE TITLE
Not able to play any nhl feeds or no recap feeds showing up at all

### ISSUE THREAD

**Issue by MaDTaZ** [crobibero/Emby.Plugins.LazyMan#3]
When I refresh it will not show any feed for most of the games.  I also found that there are never any recap feeds

**Comment by crobibero** [comment]
https://emby.media/community/index.php?/topic/77617-emby4-internet-channel-plugin-loads-every-video-from-api/#entry788276

Change the trigger for "Refresh Internet Channels" to 15 minutes (the lowest interval)

**Comment by MaDTaZ** [comment]
Thanks that worked perfectly
