### ISSUE TITLE
Emby Plugin Not working

### ISSUE THREAD

**Issue by xNeRv3** [crobibero/Emby.Plugins.LazyMan#4]
I installed the plugin on the Emby server running on my Windows 10 PC.  I updated the hosts file as well.  When viewing the plugin in Emby I have the MLB and NHL options as well as 3 other options showing for example: "mf.svc.nhl.com IP ERROR".  What am I missing?  I can provide screenshots if needed.  Thank you.

**Comment by crobibero** [comment]
How are you running emby?
If you have those IP error tiles then the emby server doesn't see the IP correctly
