### ISSUE TITLE
Only showing archived games

### ISSUE THREAD

**Issue by jsampson80** [crobibero/Emby.Plugins.LazyMan#5]
Hey, plugin on Emby windows 10 and Lg smart tv only shows archived games

**Comment by jordandev** [comment]
Same here. Can see Sept 17th but nothing for Sept 18

**Comment by samirp91** [comment]
Same here on Samsung TV. Can't see NHL games for Sept 18.

**Comment by samirp91** [comment]
I'm getting the message "Stream URL is expired". I'm assuming it has something to do with the way you're checking the URL expiry date. @crobibero

**Comment by crobibero** [comment]
I think I'll have to do some refactoring- Emby keeps caching the channel even though I tell it not to

**Comment by jordandev** [comment]
Wouldn’t reinstalling(+restarting) the plugin have cleared that cache?

**Comment by crobibero** [comment]
https://emby.media/community/index.php?/topic/77617-emby4-internet-channel-plugin-loads-every-video-from-api/#entry788276

Change the trigger for "Refresh Internet Channels" to 15 minutes (the lowest interval)
