### ISSUE TITLE
Streams list not up to date

### ISSUE THREAD

**Issue by mathg** [crobibero/Emby.Plugins.LazyMan#7]
There seems to be an issue with the visible streams in Emby vs what we can see in Lazyman.

Currently when opening Lazyman, I can see 4 NHL games, but when browsing the games on Emby, there are no games shown. 

Same thing happened yesterday and I got yesterday's game available much after they were started/completed.

My "Refresh Internet Channels" task is set to 15 minutes so if the source come from the same place as Lazyman, I'm guessing they should show up correctly.

**Comment by samirp91** [comment]
Which version are you using?

**Comment by mathg** [comment]
Emby plugins is 6.0 and Emby is 4.2.1.0

I do encounter that problem everyday. It just looks like the list is updated much later than the current day, so right now, I have the games for yesterday, which were not available yesterday and today the list is empty.

**Comment by samirp91** [comment]
Seems like it might be a cache issue or it wasn't reinstalled again. Follow these steps. 

1) Go to the plugins folder and delete the lazyman plugin.
2) Exit the emby server.
3) Go up one folder to programdata and delete the cache. 
4) Start up the emby server. 
5) Check if lazyman plugin is still there. 
If it is, repeat steps 1-5. (Sometimes it reinstalls)
6) Exit emby server
7) Delete cache
8) Place latest lazyman plugin into the plugins folder 
9) Start up the server.

**Comment by mathg** [comment]
Thanks @samirp91 this did the trick to have the games back!
