### ISSUE TITLE
MLB Streams broken

### ISSUE THREAD

**Issue by jeid64** [crobibero/Emby.Plugins.LazyMan#8]
Howdy, using latest Emby/LazyMan plugin. I'm trying to play some MLB games, but get "No compatible streams" for everything. Looking over the plugin logs I see
https://pastebin.com/2c0in9ve
it seems like its failing to talk to freegamez to fetch stream URLs. NHL works fine, but all MLB games contain response NOT for some reason. Is it possible the plugin is crafting the request to freegames incorrectly?

**Comment by crobibero** [comment]
Is this still an issue? I know MLB was down recently
